name = "flarefilter-worker"
main = "src/index.ts"
compatibility_date = "2024-02-08"

# The Worker runs frequently (e.g., every minute), but the ACTUAL execution per tenant is completely dynamic.
# D1 decides if a tenant is due for a check (e.g., this tenant wants checks every 5 mins, that tenant wants checks every 10 mins).
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "flarefilter-db"
database_id = "08d3a032-70b5-4541-93f3-2dac72079d3b"
migrations_dir = "../../packages/db/migrations"

[[kv_namespaces]]
binding = "BLOCKLIST"
id = "5d2ee0304b234b50a2aa0ea58e6c7f88"
